// Mirror extension/ into app/clipper/bundle.js.
//
// Same reasoning as sync-demo.mjs: the app has no build step, so it cannot
// read extension/ at runtime — but the Settings screen has to hand the user a
// zip of exactly that folder. GitHub can only zip a whole repository, and a
// release asset would be a second artefact to keep in step with the code.
//
//     node scripts/sync-clipper.mjs          # write
//     node scripts/sync-clipper.mjs --check  # exit 1 if stale
//
// Base64 because the folder is not all text: two PNG icons are in there. The
// module is imported *dynamically*, only when someone clicks Download, so its
// ~310KB never touches the boot path.
//
// NOT under app/vault/ — sync-extension.mjs mirrors that directory back INTO
// extension/, so a bundle living there would be packed into the next bundle,
// and the next, and the next.

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync } from "node:fs";
import { join, dirname, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const EXT_DIR = join(ROOT, "extension");
export const OUT = join(ROOT, "app", "clipper", "bundle.js");

/** Every file in extension/, as POSIX paths relative to it, sorted. */
export function clipperFiles() {
  const out = [];
  (function walk(dir) {
    for (const entry of readdirSync(dir).sort()) {
      if (entry.startsWith(".")) continue;      // .DS_Store and friends
      const p = join(dir, entry);
      statSync(p).isDirectory() ? walk(p) : out.push(relative(EXT_DIR, p).split(sep).join("/"));
    }
  })(EXT_DIR);
  return out.sort();
}

export function render() {
  const files = clipperFiles();
  const entries = files.map((f) => {
    const b64 = readFileSync(join(EXT_DIR, f)).toString("base64");
    return `  [${JSON.stringify(f)}, "${b64}"],`;
  });
  return [
    "// GENERATED by scripts/sync-clipper.mjs — do not edit.",
    "// Source of truth is extension/. Regenerate with:",
    "//     node scripts/sync-clipper.mjs",
    "//",
    "// [path relative to the extension root, base64 of the bytes].",
    `/** ${files.length} files. */`,
    "export const CLIPPER_BUNDLE = [",
    ...entries,
    "];",
    "",
  ].join("\n");
}

const text = render();
const check = process.argv.includes("--check");
let current = null;
try { current = readFileSync(OUT, "utf8"); } catch (_) {}

if (check) {
  if (current !== text) {
    console.error("✗ app/clipper/bundle.js is stale — run: node scripts/sync-clipper.mjs");
    process.exit(1);
  }
  console.log(`✓ app/clipper/bundle.js is in sync with extension/ — ${clipperFiles().length} files`);
} else if (current === text) {
  console.log("✓ app/clipper/bundle.js already up to date");
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, text);
  console.log(`✓ wrote app/clipper/bundle.js from ${clipperFiles().length} files`);
}
